---
title: "Klimafremskrivning 24"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r include=FALSE}

library(tidyverse)
library(flexdashboard)
library(data.table)
library(highcharter)
library(TRMvisual)
library(fontawesome)

sti <- "S:/CKA/Databank/007 Klimafremskrivning/tidy_datasaet/"

data <- dir(sti) %>% 
  str_subset(".csv") |> 
  (\(y) map(y, ~fread(str_c(sti,.x)) %>% 
              mutate(drivmiddel =case_when(drivmiddel =="BEV"~"El",
                                           drivmiddel =="PHEV"~"Plug-in-hybrid",
                                           drivmiddel =="Total"~"Drivmidler i alt",
                                           drivmiddel =="Øvrige"~"Oevrige",
                                           T ~drivmiddel) |>
                       str_squish() %>% 
           factor(levels = rev(c("El", "Plug-in-hybrid","Brint",
                             "Benzin", "Diesel", "Gas", "Oevrige",
                             "Drivmidler i alt")))
           )) %>% 
     set_names(str_remove_all(y, "_kf24.csv")))()

farver <- c(trm_colors(c("groen",  "orange", "blaa", "gul", "graa")), "#d49e02", "#0087b3") 
names(farver) <- c("El", "Plug-in-hybrid","Benzin", "Diesel", "Oevrige", "Brint", "Gas")



til_fig_udl <- data[["udledninger"]] %>% 
  filter(type!="Total") %>% 
  mutate(type = str_replace_all(type, "definieret", "defineret") %>% 
           {ifelse(.=="Sektor detaljer ikke defineret", "Ikke defineret", .)} %>% 
           factor(levels = rev(c( "Grænsehandel","Personbiler", "Varebiler", "Lastbiler","Busser","Motorcykler",
                             "Banetransport",
                             "Indenrigs søfart",
                             "Lufttransport, indenrigs",  "Grønland & Færøerne",
                             "Øvrige Transport",  "Ikke defineret"))))

farver_udl <- c( "#0087b3",trm_colors(c( "blaa", "orange", "groen", "gul", "lyseblaa")),
                trm_colors("blaa"),
                trm_colors("blaa"),
                trm_colors(c("blaa", "orange")),
                trm_colors(c("blaa", "graa")))
                
names(farver_udl) <- c( "Grænsehandel","Personbiler", "Varebiler", "Lastbiler","Busser","Motorcykler",
                             "Banetransport",
                             "Indenrigs søfart",
                             "Lufttransport, indenrigs",  "Grønland & Færøerne",
                             "Øvrige Transport",  "Ikke defineret")


til_fig_udl_tot <- data[["udledninger"]] %>% 
  filter(type=="Total") %>% 
  mutate(sektor = factor(sektor, levels = rev(c( "Vejtransport", "Banetransport", "Luftfart", "Søfart", "Øvrige transport" )))) %>% 
  arrange(sektor, aar)

farver_udl_tot <- trm_colors(c("groen", "gul","graa", "orange", "blaa"))
  

til_fig <- map_dfr(c("bestand", "salg"), ~data[[.x]] %>% 
                      mutate(type_KF = .x)) %>% 
  # add_column(summarise(.,n_driv = n_distinct(drivmiddel),
  #                      .by = "type")) %>% 
  filter(!(underkat=="Total" & drivmiddel=="Drivmidler i alt")) %>% 
  summarise(vaerdi = sum(vaerdi),
            .by = c("type_KF", "type", "drivmiddel", "aar"))


best_fig_fkt <- function(input, input_type){
  
  input1 <- til_fig %>% 
    filter(type==input, type_KF==input_type ) %>% 
    arrange(drivmiddel, aar)
  
  farver_end <- input1 %>% inner_join(enframe(farver, name = "drivmiddel", value = "farve")) %>% distinct(drivmiddel, farve) %>% deframe() %>% unname() %>% as.character()

  
  input1 %>% 
    hchart('area', hcaes(x = aar, y =vaerdi, group = drivmiddel  ), borderColor = 0, 
           marker = FALSE,style = list(useHTML = TRUE, font = "Georgia")) %>%
    hc_plotOptions(series = list(stacking = "normal", lineWidth = 0)) %>% 
    # },
    # select: {
    #   enabled: false
    # }
    hc_colors(farver_end) |>
    # hc_colors(c(trm_colors(farver))) |>
    hc_yAxis(title = list(text = "Antal"),
           labels = list(formatter = JS("function() {
    if (this.value >= 1000000) {
        return (this.value / 1000000).toFixed(0) + ' Mio.';
    } else if (this.value >= 1000) {
        return (this.value / 1000).toFixed(0) + ' tus.';
    } else {
        return this.value.toLocaleString();
    }
}"))) %>% 
    hc_xAxis(title = list(text = "")) %>% 
    hc_tooltip(shared = TRUE,
               pointFormat = str_glue("<b>{{series.name}}</b>: {{point.y:,.0f}} {str_to_lower(input)} ({{point.percentage:.1f}} pct.)) <br>")
    ) %>% 
    hc_legend(reversed =TRUE) %>%
    hc_tooltip(shared = TRUE)  %>% 
    trm_hc_format(titel =str_glue("<b>{input}" ))
}



udl_fig_fkt <- function(input){
  
  input1 <- til_fig_udl %>% 
    filter(sektor==input) %>% 
    arrange(type, aar)
  
  farver_end <- input1 %>% inner_join(enframe(farver_udl, name = "type", value = "farve")) %>% distinct(type, farve) %>% deframe() %>% unname() %>% as.character()
  
  
  input1 %>% 
    hchart('area', hcaes(x = aar, y =vaerdi, group = type  ), borderColor = 0, 
           marker = FALSE,style = list(useHTML = TRUE, font = "Georgia")) %>%
    hc_plotOptions(series = list(stacking = "normal", lineWidth = 0)) %>% 
    # },
    # select: {
    #   enabled: false
    # }
    hc_colors(farver_end) |>
    # hc_colors(c(trm_colors(farver))) |>
        hc_yAxis(title = list(text = "Antal"),
           labels = list(formatter = JS("function() {
    if (this.value >= 1000000) {
        return (this.value / 1000000).toFixed(0) + ' Mio.';
    } else if (this.value >= 1000) {
        return (this.value / 1000).toFixed(0) + ' tus.';
    } else {
        return this.value.toLocaleString();
    }
}"))) %>% 
    
    hc_xAxis(title = list(text = "")) %>% 
    hc_tooltip(shared = TRUE) %>% 
    hc_legend(reversed =TRUE
              # layout = "horizontal",     # Ensures a horizontal layout
              # align = "center",          # Center-aligns the legend
              # verticalAlign = "bottom",  # Places the legend at the bottom
              ) %>%
              hc_tooltip(shared = TRUE,
                         pointFormat = "<b>{series.name}</b>: {point.y:,.0f} t ({point.percentage:.1f} pct.)) <br>")  %>% 
                trm_hc_format(titel =str_glue("<b>{input}" ))
}



```

```{r}
tags$style("
  .chart-container {
    width: 100% !important;
  }
")
```


`r fa("temperature-arrow-down")` Udledninger 
===================================== 

 <br />
&nbsp;&nbsp; Ønskes et adgang til alle datasættene kan de tilgås her: <b> S:\\CKA\\Databank\\007 Klimafremskrivning\\KF24_dataark_Transport.xlsx </b>

Row {data-height=auto}
-------------------------------------

```{r}

til_fig_udl_tot %>% 
  mutate(vaerdi = vaerdi/1000000) %>% 
    hchart('area', hcaes(x = aar, y =vaerdi, group = sektor  ), borderColor = 0, 
           marker = FALSE,style = list(useHTML = TRUE, font = "Georgia")) %>%
    hc_plotOptions(series = list(stacking = "normal", lineWidth = 0)) %>% 
    # },
    # select: {
    #   enabled: false
    # }
    hc_colors(farver_udl_tot) |> 
  hc_chart(
    width = NULL  # Forces responsive width
  ) %>% 
    # hc_colors(c(trm_colors(farver))) |>
    # hc_yAxis(title = list(text = "Antal (Mio.)"),
    #          labels = list(formatter = JS("function() {
    #   return this.value.toLocaleString();
    # }"))) |> 
    hc_yAxis(title = list(text = "Antal"),
           labels = list(formatter = JS("function() {
        return this.value.toString()  + ' Mio.';
    }"))) %>% 
    hc_xAxis(title = list(text = "")) %>% 
  
    hc_tooltip(shared = TRUE, 
               pointFormat = paste("<b>{series.name}</b>: {point.y:,.1f} mio. t. CO2 ({point.percentage:.1f} pct.) <br>")
    ) %>% 
    hc_legend(reversed =TRUE) %>%
    hc_tooltip(shared = TRUE)  %>% 
    trm_hc_format(titel ="<b>Samlede udledninger fra transportsektoren")

```



Row
-------------------------------------

```{r}
udl_fig_fkt("Vejtransport")
```
    
        
```{r}
udl_fig_fkt("Banetransport")
```

Row {data-height=350}
-------------------------------------

```{r}
udl_fig_fkt("Søfart")
```
    
        
```{r}
udl_fig_fkt("Luftfart")
```

Row 
-------------------------------------

```{r}
udl_fig_fkt("Øvrige transport")
```
    
        

Bestand {data-icon="fa-solid fa-car-side"}
===================================== 


Row
-------------------------------------

```{r}
best_fig_fkt("Personbiler", "bestand")
```
    
        
```{r}
best_fig_fkt("Varebiler", "bestand")
```

Row
-------------------------------------

```{r}

best_fig_fkt("Lastbiler", "bestand")

```
    
```{r}

best_fig_fkt("Busser", "bestand")

```
    
Row
-------------------------------------

```{r}

best_fig_fkt("Motorcykler", "bestand")

```
   
    
`r fa("chart-line")` Salg
===================================== 
    
    
Row
-------------------------------------

```{r}

# map( unique(til_fig_best %>% pull(type)),
#      ~best_fig_fkt(.x))

best_fig_fkt("Personbiler", "salg")

```
    
        
```{r}
best_fig_fkt("Varebiler", "salg")
```

Row 
-------------------------------------

```{r}

best_fig_fkt("Lastbiler", "salg")

```
    
```{r}

best_fig_fkt("Busser", "salg")

```
    
Row 
-------------------------------------

```{r}

best_fig_fkt("Motorcykler", "salg")

```
   