---
title: "præsentation togkontoret"
output:
  powerpoint_presentation:
    reference_doc: "Præsentation2.pptx"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,dev = "png", 
                      dev.args = list(type = "cairo"), dpi = 220)
library(data.table)
library(base64enc)
library(gridExtra)


library(tidyverse)
library(readxl)
library(sf)
library(TRMvisual)
library(extrafont)
library(statbank)
library(highcharter)
library(knitr)
library(extrafont)
library(ggpp)
library(officer)
library(lubridate)
library(plotly)
library(scales)
library(downloadthis)
library(htmltools)
library(rvg)
library(grid)
 
extrafont::loadfonts()

left_margin <- -10
text_size <- 9

tog_pres_theme <-  theme(
    text = element_text(family = "Georgia", colour = "#333333"),
    plot.margin = ggplot2::margin(t = 30, r = 20),
    axis.ticks = ggplot2::element_blank(),
     legend.position="bottom",
    # legend.margin = ggplot2::margin(b = 0.5, unit = "cm"),
    legend.key.height = grid::unit(0.4, 'cm'),
    legend.spacing.y = grid::unit(0.4, 'cm'),
    legend.background = ggplot2::element_rect(fill = "#ECECEC" ),
    # legend.text = element_text(color = "#A0A0A0"),
    # legend.text = ggplot2::element_text( size = text_size,
    #                                      margin = ggplot2::margin(r = 100, unit = "pt")),
    plot.background = ggplot2::element_rect(fill = "#ECECEC"),
                     panel.grid.major.x = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_line(color = "#A0A0A0",
                                                          size = 0.1),
    axis.text = ggplot2::element_text(size = text_size, family = "Georgia"),
    legend.title = element_blank(),
    plot.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y.left = ggplot2::element_text( vjust = 1.05, angle =0,
                                               margin = ggplot2::margin(r = left_margin,
                                                                        t = 0, b = 0, l = 10),
                                               size = text_size)
    )



Sys.setlocale("LC_TIME", "da_DK.UTF-8")
data_til_fig <- fread("S:/TRM Databank/012 Togkontoret/Kundepunktlighed.csv")
data_til_fig_MDBF <- fread("S:/TRM Databank/012 Togkontoret/MDBF.csv")

md_lvls <-  c("jan", "feb", "mar", "apr", "maj", "jun",
              "jul", "aug", "sep", "okt", "nov", "dec", 
              "aar_til_dato")

md_aar <- data_til_fig %>%
  filter(maaned!="aar_til_dato" & tog_type=="fjern_og_regionaltog" & type=="Kundepunktlighed" ) %>%  
    mutate(maaned_num = month(dmy(paste0("01-", maaned, "-2024"), locale = "da_DK"))) %>% 
  arrange(aar, maaned_num) %>% 
  distinct(aar, maaned) %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>%
  pull(aar_md)

lvls <- md_aar %>% 
  tail(13)

indev_aar <- md_aar %>% str_extract_all("\\d{4}$", simplify = T) %>% as.numeric() %>% max()
sidste_aar <- md_aar %>% str_extract_all("\\d{4}$", simplify = T) %>% as.numeric() %>% max()-1

indev_md <- md_aar %>% str_extract_all("^\\D{3}", simplify = T) %>% tail(1) %>% deframe()
sidste_md <- md_aar %>% str_extract_all("^\\D{3}", simplify = T) %>% .[nrow(.)-1]

  #figur 1
fig_kunde <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"fjern_og_regionaltog"),
         aar_md %in% lvls)

gnst_tal <- fig_kunde %>% summarise(gnst = mean(pct),
                        .by = "type") %>% deframe()

md_under <- fig_kunde %>% pivot_wider(names_from = "type", values_from = "pct") %>% 
  mutate(tjek = Kundepunktlighed <Kontraktkrav) %>% 
  pull(tjek) %>% sum()

fig_kunde_1 <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"fjern_og_regionaltog"),
         aar_md %in% tail(md_aar, 24)[1:12])

md_under_1 <- fig_kunde_1 %>% pivot_wider(names_from = "type", values_from = "pct") %>% 
  mutate(tjek = Kundepunktlighed <Kontraktkrav) %>% 
  pull(tjek) %>% sum()


#figur 2

fig_2 <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"fjern_og_regionaltog"),
         type=="Kundepunktlighed",aar %in% c((indev_aar-3):indev_aar)) %>% 
  mutate(maaned = factor(maaned, levels = md_lvls),
         aar = as.character(aar),
    maaned_num = month(dmy(paste0("01-", maaned, "-2024"), locale = "da_DK"))) %>% 
  arrange(aar, maaned_num)


# figur 3
fig_3 <- data_til_fig %>%
   mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned==indev_md[[1]], str_detect(tog_type,"fjern_og_regionaltog"),
         type=="Kundepunktlighed",aar %in% c((indev_aar-10):indev_aar)) %>% 
    mutate(maaned_num = month(dmy(paste0("01-", maaned, "-2024"), locale = "da_DK"))) %>% 
  arrange(aar, maaned_num)


# figur 4
fig_stog <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"s_tog"),
         aar_md %in% lvls)


md_under_stog <- fig_stog %>% pivot_wider(names_from = "type", values_from = "pct") %>% 
  mutate(tjek = Kundepunktlighed <Kontraktkrav) %>% 
  pull(tjek) %>% sum()

gnst_stog <- fig_stog %>% summarise(gnst = mean(pct),
                        .by = "type") %>% deframe()

fig_stog_1 <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"s_tog"),
         aar_md %in% tail(md_aar, 24)[1:12])

md_under_stog_1 <- fig_stog_1 %>% pivot_wider(names_from = "type", values_from = "pct") %>% 
  mutate(tjek = Kundepunktlighed <Kontraktkrav) %>% 
  pull(tjek) %>% sum()

# figur 5

fig_stog_3aar <- data_til_fig %>%
  mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned!="aar_til_dato", str_detect(tog_type,"s_tog"),
         type=="Kundepunktlighed",aar %in% c((indev_aar-3):indev_aar)) %>% 
  mutate(aar = as.character(aar),
         maaned_num = month(dmy(paste0("01-", maaned, "-2024"), locale = "da_DK"))) %>% 
  arrange(aar, maaned_num)

# figur 6
fig_stog_10aar <- data_til_fig %>%
   mutate(aar_md = str_c(maaned, " ", aar)) %>% 
  filter(maaned==indev_md[[1]], str_detect(tog_type,"s_tog"),
         type=="Kundepunktlighed",aar %in% c((indev_aar-10):indev_aar)) %>% 
    mutate(maaned_num = month(dmy(paste0("01-", maaned, "-2024"), locale = "da_DK"))) %>% 
  arrange(aar, maaned_num)

#MDBF figurerne

fig_MDBF <- data_til_fig_MDBF %>% 
  mutate(maaned = factor(maaned, levels = md_lvls), 
    type = ifelse(type=="IC1-vogne", "IC1", type) %>% 
           factor(levels = c("Dobbeltdækkere", "IC1", "EB", "IC3", "IC4", "IR4", "SA/SE"))) %>% 
  filter(aar==indev_aar & maaned %in% c(sidste_md, indev_md) | aar==sidste_aar & maaned=="aar_til_dato")
  
# fig_MDBF_2 <- data_til_fig_MDBF %>% 
#   filter(maaned!="aar_til_dato" & aar >indev_aar-3) %>% 
#   summarise(km = sum(km, na.rm = T),
#     .by = c("aar", "maaned")
#   ) %>% 
#   mutate(maaned = factor(maaned, levels = md_lvls)) %>% 
#   arrange(aar, maaned) %>% 
#   mutate(akk_km = cumsum(coalesce(km,0)),
#          km_12 = (akk_km-lag(akk_km,12))/12)

```

# Centrale hovedpointer

- [pointe 1] 

- [pointe 2] 

- [pointe 3] 


# Figur 1: Seneste tolv måneders kundepunktlighed
```{r fig.width=10, fig.height=5}

ggplot(fig_kunde) +
  geom_line(linewidth = 1, aes(x = fct(aar_md), y = pct, group = type, color = type, linetype = type)) +
  scale_color_manual(values = c("Kundepunktlighed" = trm_colors("blaa"), 
                                "Kontraktkrav" = "black")) +
  scale_linetype_manual(values = c("Kundepunktlighed" = "solid", 
                                   "Kontraktkrav" = "dashed")) +
  scale_y_continuous(limits = c(50, 100)) +
  labs(y = "Pct.",
       x = NULL) +
  tog_pres_theme
  # TRMvisual::theme_trm(-40, 100, 9)
  

```


# Figur 2: Månedsvis DSB F&R kundepunktlighed – sammenlignet med tidligere år
```{r fig.width=10, fig.height=5}

farver <- c("blaa","orange", "groen","gul", "graa")
farvekoder <- trm_colors(farver)  # f.eks. named vector: c("blaa"="#003366",...)


fig2_plot <- ggplot(fig_2 %>% filter(type == "Kundepunktlighed")) +
  geom_line(linewidth = 1,
       aes(x = maaned, y = pct, group=aar, color = aar)) +
  scale_color_manual(values = farvekoder) +
  scale_y_continuous(limits = c(50, 100), name = "Pct.") +
  labs(x = NULL) +
  tog_pres_theme

fig3_plot <- ggplot(fig_3 %>% filter(type == "Kundepunktlighed")) +
  geom_line(aes(x = aar_md, y = pct, group = 1), color = trm_colors("blaa"), linewidth = 1) +
  scale_y_continuous(limits = c(60, 100), name = "Pct.") +
  labs(x = NULL) +
  tog_pres_theme
```


```{r fig.width=10, fig.height=5}
grid.arrange(fig2_plot, fig3_plot, ncol = 2)

```

# Figur 3: Månedsvis DSB S-tog kundepunktlighed

```{r fig.width=10, fig.height=5}
ggplot(fig_stog) +
  geom_line(linewidth = 1, aes(x = fct(aar_md), y = pct, group = type, color = type, linetype = type)) +
  scale_color_manual(values = c("Kundepunktlighed" = trm_colors("blaa"), 
                                "Kontraktkrav" = "black")) +
  scale_linetype_manual(values = c("Kundepunktlighed" = "solid", 
                                   "Kontraktkrav" = "dashed")) +
  scale_y_continuous(limits = c(84, 100)) +
  labs(y = "Pct.",
       x = NULL) +
  tog_pres_theme
```


# Figur 4: Månedsvis DSB S-tog kundepunktlighed – sammenlignet med tidligere år
```{r}
farver <- c("blaa","orange", "groen","gul", "graa")
farvekoder <- trm_colors(farver)  # f.eks. named vector: c("blaa"="#003366",...)


fig4_plot <- ggplot(fig_stog_3aar %>% filter(type == "Kundepunktlighed")) +
  geom_line(linewidth = 1,
       aes(x = fct(maaned), y = pct, group=aar, color = aar)) +
  scale_color_manual(values = farvekoder) +
  scale_y_continuous(limits = c(85, 100), name = "Pct.") +
  labs(x = NULL) +
  tog_pres_theme 

fig5_plot <- ggplot(fig_stog_10aar %>% filter(type == "Kundepunktlighed")) +
  geom_line(aes(x = aar_md, y = pct, group = 1), color = trm_colors("blaa"), linewidth = 1) +
  scale_y_continuous(limits = c(85, 100), name = "Pct.") +
  labs(x = NULL) +
  tog_pres_theme
```


```{r fig.width=10, fig.height=5}
grid.arrange(fig4_plot, fig5_plot, ncol = 2)

```

# Figur 5: Månedsvis MDBF sammenlignet med foregående måned og år

```{r fig.width=10, fig.height=5}

# Forbered data
data_bar <- fig_MDBF %>%
  filter(aar == indev_aar) %>%
  mutate(maaned = factor(maaned, levels = c(sidste_md, indev_md)))

data_point <- fig_MDBF %>%
  filter(aar == sidste_aar & maaned == "aar_til_dato")

# Lav plottet
ggplot() +
  # Søjler for nuværende år (to måneder)
  geom_col(data = data_bar,
           aes(x = type, y = km, fill = maaned),
           position = position_dodge(width = 0.7), width = 0.6) +
  
  # Punkter (diamanter) for forrige år
  geom_point(data = data_point,
             aes(x = type, y = km),
             shape = 23,  # Diamond shape
             size = 3.5,
             fill = "black",
             color = "black") +

  scale_fill_manual(values = trm_colors(c("blaa", "orange"))) +
  labs(y = "km",
       x = NULL) +
  scale_y_continuous(limits = c(0, 80000)) +
  tog_pres_theme
```

