---
title: "Varebiler"
output:
  html_document:
    css: styles.css
date: 'Opdateret `r format(Sys.Date(), "%d. %B %Y")`'
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
extrafont::loadfonts()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE )

library(tidyverse)
library(readxl)
library(sf)
library(TRMvisual)
library(extrafont)
library(statbank)
library(highcharter)
library(knitr)
library(extrafont)
library(ggpp)
library(officer)
library(lubridate)
library(plotly)
library(scales)
library(downloadthis)


lang <- getOption("highcharter.lang")
lang$decimalPoint <- ","
lang$thousandsSep <- "."
lang$numericSymbols <- highcharter::JS("null") # optional: remove the SI prefixes
options(highcharter.lang = lang)


options(scipen = 100, digits = 2, OutDec = ",")
Sys.setenv(Lang = "da")

knit_hooks$set(inline = function(x) {
  if(is.numeric(x)){
    return(prettyNum(x, big.mark=".", digits = 2))
  } else{
    return(x)
  }
})

if(month(Sys.Date())==1){
  stjerne <- ""
  stjerne_tekst <- ""
} else{
  stjerne <- "*"
  stjerne_tekst <- "*År til dato"
}

sti_kf <- "S:/CKA/Databank/007 Klimafremskrivning"

#Data til bestand
# Laver variable til BRUG og datasæt
brug_values <- c("1000", "1100", "1200")
dataset_names <- c("data_bil", "data_husholdning", "data_erhverv")

# Laver data
process_data <- function(brug_values) {
  tbl_dst("BIL54", "da") %>% 
    filter(BILTYPE %in% c("4000102000"), OMRÅDE == "000", BRUG %in% brug_values) %>% 
    use_labels() %>% 
    collect() %>% 
    select(-c("OMRÅDE", "BRUG")) %>% 
    mutate(DRIV = ifelse(str_detect(DRIV, "hybrid"), "Plug-in-hybrid", DRIV),
           DRIV = ifelse(DRIV %in% c("Drivmidler i alt", "Benzin", "Diesel", "El", "Plug-in-hybrid"),
                         DRIV,
                         "Øvrige drivmidler")) %>% 
    summarise(INDHOLD = sum(INDHOLD), .by = c("DRIV", "TID"))
}

# Laver loop/map
dataset <- map(brug_values, process_data)

# Laver datasæt til objekter
list2env(setNames(dataset, dataset_names), envir = .GlobalEnv)


data_bil_1 <- data_bil |>
  mutate(
    AAR = round(as.numeric(str_sub(TID, end = 4)) + (as.numeric(str_sub(TID, start = -2)) - 1) / 12, 3),
    DATE = as.Date(str_c(str_sub(TID, end = 4), "-", str_sub(TID, start = -2), "-01")),
    DATE_1 = DATE %m+% months(1),
    UDV_BIL = INDHOLD - lag(INDHOLD),
    .by =  "DRIV"
  )

#Data til nysalg
# Laver variable til datasæt
dataset_names_2 <- c("data_nysalg", "data_nysalg_husholdning", "data_nysalg_erhverv")

# Laver data
process_data_2 <- function(brug_values) {
  tbl_dst("BIL53", "da") %>% 
    filter(BILTYPE %in% c("4000102000"), OMRÅDE == "000", BRUG %in% brug_values) %>% 
    use_labels() %>% 
    collect() %>% 
    select(-c("OMRÅDE", "BRUG")) %>% 
    mutate(DRIV = ifelse(str_detect(DRIV, "hybrid"), "Plug-in-hybrid", DRIV),
           DRIV = ifelse(DRIV %in% c("Drivmidler i alt", "Benzin", "Diesel", "El", "Plug-in-hybrid"),
                         DRIV,
                         "Øvrige drivmidler")) %>% 
    summarise(INDHOLD = sum(INDHOLD), .by = c("DRIV", "TID"))
}

# Laver loop/map
dataset_2 <- map(brug_values, process_data_2)

# Laver datasæt til objekter
list2env(setNames(dataset_2, dataset_names_2), envir = .GlobalEnv)


Nummer_sidste_md <- data_nysalg |> 
  slice_tail(n=1) |> 
  pull(TID) |> 
  (\(y) ifelse(str_sub(y, start = -2, end = -2) == "0", str_sub(y, start = -1), str_sub(y, start = -2)))()


nyeste_aar <- data_nysalg |> 
  slice_tail(n=1) |> 
  pull(TID) |> 
  (\(y) str_c(str_sub(y, end = 4)))()


max_aar <- as.numeric(nyeste_aar)
# legend_sort <- c("El", "Plug-in-hybrid", "Diesel","Benzin","Øvrige drivmidler", "Drivmidler i alt")
legend_sort <- c("Øvrige drivmidler", "Benzin", "Diesel", "Plug-in-hybrid", "El" , "Drivmidler i alt")

data_nysalg_1 <- data_nysalg |> 
  mutate(AAR = str_sub(TID, end = 4)) |> 
  (\(y) bind_rows(group_by(y, AAR, DRIV) |> 
                    summarise(INDHOLD = sum(INDHOLD),
                              .groups = "drop_last") |> 
                    mutate(A_INDHOLD = round(INDHOLD/sum(INDHOLD, na.rm = T)*100 ,1)) |> 
                    ungroup(), 
                  filter(y, TID==max(TID)) |> 
                    summarise(AAR = str_c(str_sub(TID, end = 4), " (",
                                          format(ISOdate(2000, str_sub(TID, start = -2), 1), "%B"),")"),
                              INDHOLD = sum(INDHOLD),
                              .by = "DRIV") |> 
                    mutate(A_INDHOLD = round(INDHOLD/sum(INDHOLD, na.rm = T)*100, 1)) |> 
                    ungroup()))() |> 
  mutate(DRIV = factor(DRIV, levels = legend_sort))


data_nysalg_3<- data_nysalg |> 
  mutate(DRIV = ifelse(str_detect(DRIV, "hybrid"), "Plug-in-hybrid", DRIV),
         AAR = str_sub(TID)) |> 
  group_by(AAR, DRIV) |> 
  summarise(INDHOLD = sum(INDHOLD),
            .groups = "drop_last") |> 
  mutate(A_INDHOLD = round(INDHOLD/sum(INDHOLD)*100 ,1)) |> 
  ungroup()|> 
  mutate(DRIV = factor(DRIV, levels =legend_sort))

data_nysalg_2 <- data_nysalg |> 
  mutate(DRIV = ifelse(str_detect(DRIV, "hybrid"), "Plug-in-hybrid", DRIV),
         AAR = str_sub(TID, end = 4)) |> 
  group_by(AAR, DRIV) |> 
  summarise(INDHOLD = sum(INDHOLD, na.rm = T),
            .groups = "drop_last") |> 
  mutate(A_INDHOLD = round(INDHOLD/sum(INDHOLD)*100 ,1)) |> 
  ungroup() |> 
  mutate(DRIV = factor(DRIV, levels =legend_sort),
         year = as.numeric(AAR))


data_nysalg_3 <- data_nysalg_3 %>%
  mutate(year = year(ymd(paste0(AAR, "01"))),
         month = month(ymd(paste0(AAR, "01")))) %>%
  mutate(formatted_date = paste(format(ISOdate(2000, month, 1), "%B"), year)) # Use the Danish month names and the year to create the desired format

Måned_max_EL_andel <- data_nysalg_3 %>%
  filter(DRIV=="El") %>%
  slice(which.max(A_INDHOLD)) %>%
  pull(formatted_date)


Værdi_max_EL_andel <- data_nysalg_3 %>%
  filter(DRIV=="El") %>%
  slice(which.max(A_INDHOLD)) %>%
  pull(A_INDHOLD)


```

```{r}
totalsalg <- data_nysalg_1 %>%
  filter(AAR == nyeste_aar) %>%
  summarize(sum_indhold = sum(INDHOLD))


fbil_andel_nysalget19 <- data_nysalg_1 %>%
  filter(AAR ==2019) %>%
  filter(DRIV %in% c("Benzin", "Diesel")) %>%  # Filter for values 1 and 2 in 'drit'           # Group by 'AAR'
  summarize(Sum_A_INHOLD = sum(A_INDHOLD)) # Calculate the sum of 'A_INHOLD' for each 'AAR'


fbil_andel_nysalget <- data_nysalg_1 %>%
  filter(AAR ==nyeste_aar) %>%
  filter(DRIV %in% c("Benzin", "Diesel")) %>%  # Filter for values 1 and 2 in 'drit'
  summarize(Sum_A_INHOLD = sum(A_INDHOLD))  # Calculate the sum of 'A_INHOLD' for each 'AAR'

pihb_andel <- data_nysalg_1 %>%
  filter(AAR ==2021) %>%
  filter(DRIV == "Plug-in-hybrid") %>%  # Filter for values 1 and 2 in 'drit'
  summarize(Sum_A_INHOLD = sum(A_INDHOLD))  # Calculate the sum of 'A_INHOLD' for each 'AAR'

ebil_andel_nysalget19 <- data_nysalg_1 %>%
  filter(AAR ==2019) %>%
  filter(DRIV %in% ("El")) %>%  # Filter for values EL in 'drit'           # Group by 'AAR'
  summarize(Sum_A_INHOLD = sum(A_INDHOLD)) # Calculate the sum of 'A_INHOLD' for each 'AAR'


ebil_andel_nysalget <- data_nysalg_1 %>%
  filter(DRIV %in% ("El")) %>%  # Filter for values EL in 'drit'
  summarize(Sum_A_INHOLD = sum(A_INDHOLD),
            .by = "AAR")|>
  pivot_wider(names_from ="AAR", values_from = Sum_A_INHOLD)# Calculate the sum of 'A_INHOLD' for each 'AAR'


ebil_total_nysalget <- data_nysalg_1 %>%
  filter(DRIV %in% ("El")) %>%  # Filter for values EL in 'drit'           # Group by 'AAR'
  summarize(Sum_INHOLD = sum(INDHOLD),
            .by = "AAR") |> 
  pivot_wider(names_from = "AAR", values_from = "Sum_INHOLD")


#Data månedlig tilgang af elbiler til bestanden opgjort i DST og KF23

dat_fig_3 <- tibble("AAR"=round(sort(rep(2022:2026, 12)) + rep((c(1:12)-1)/12, 5), 3)) |> 
  mutate(KF_UDV = round(2467*exp(0.1713*(AAR-2022)),0 )) |> 
  inner_join(data_bil_1 |> 
               filter( DRIV=="El") |> 
               mutate(vaetg_gnst = round((lag(UDV_BIL, 2)+lag(UDV_BIL)+UDV_BIL)/3, 0)) |>  
               select(-c("DRIV","TID","INDHOLD")),
             by="AAR"
  ) |> 
  filter(AAR>=2023)

antal_el_biler_ialt <- dat_fig_3$UDV_BIL |> sum()
antal_el_biler_KF_est <- dat_fig_3$KF_UDV  |> sum()

pct_el_biler_ialt <- (antal_el_biler_ialt/antal_el_biler_KF_est-1)*100


```

```{r}
#Data til Figur ny figur 3 opgørelse af årlig bestand.

ny_figur_3 <- data_bil %>%
  mutate(
    aar = as.numeric(substr(TID, start = 1, stop = nchar(TID) - 3)),
    maaned = as.numeric(substr(TID, start = nchar(TID) - 1, stop = nchar(TID))),
    dansk_måned = str_c("(", format(ISOdate(2000, 1:12, 1), "%B")[maaned], ")"),
    dansk_måned_uden = case_when(
      (maaned == 1) ~ "januar",
      (maaned == 2) ~ "februar",
      (maaned == 3) ~ "marts",
      (maaned == 4) ~ "april",
      (maaned == 5) ~ "maj",
      (maaned == 6) ~ "juni",
      (maaned == 7) ~ "juli",
      (maaned == 8) ~ "august",
      (maaned == 9) ~ "september",
      (maaned == 10) ~ "oktober",
      (maaned == 11) ~ "november",
      (maaned == 12) ~ "december"
    ),
    rigtigt_år = case_when(
      (maaned == 12) ~ as.character(aar + 1),
      T ~ paste(as.character(aar), dansk_måned)
    ))


ny_figur_3_1 <- ny_figur_3 %>%
  filter(maaned == max(maaned),
         .by = "aar") %>%
  filter(DRIV !="Drivmidler i alt") %>%
  mutate(DRIV = factor(DRIV, levels = legend_sort))


max_måned <- ny_figur_3 |> 
  slice_tail(n=1) |> 
  pull(dansk_måned_uden)

max_aar <- ny_figur_3 |> 
  slice_tail(n=1) |> 
  pull(aar)

næst_nyeste_aar<-max_aar-1



bestand_2020 <- ny_figur_3_1 %>%
  filter(DRIV != "Drivmidler i alt", aar == 2019) %>%
  summarise(sum_indhold = sum(INDHOLD))

bestand_2023_seneste <- ny_figur_3_1 %>%
  filter(DRIV != "Drivmidler i alt", aar == max_aar,
         dansk_måned_uden == max_måned) %>%
  summarise(sum_indhold = sum(INDHOLD))

andel_elbiler <- ny_figur_3_1 %>%
  filter(DRIV != "Drivmidler i alt", aar == max_aar,
         dansk_måned_uden == max_måned) %>%
  summarise(sum_indhold = sum(INDHOLD))

vækst_siden_2020 <- round((bestand_2023_seneste-bestand_2020)/bestand_2020*100,2)


#Data til figur 4. Status for antallet af el-varebiler

DST_tal <- data_bil_1 |>
  filter(DRIV=="El", 
         DATE_1 %in% c(max(DATE_1), max(DATE_1-1) |> floor_date("years"))) |> 
  mutate(x_axis = ifelse(DATE_1 ==max(DATE_1),
                         str_c(max_måned, " ", nyeste_aar),
                         str_c("1. januar ", round(AAR,0))),
         oprindelse = "DST")

KF_bestand <- read_excel(str_c(sti_kf, "/", "KF24_dataark_Transport.xlsx"),
                         sheet = "Bestand", skip =4) %>% 
  rename("type"=1, drivmiddel = 2) %>% 
  filter(!if_all(.fns =~is.na(.x))) %>% 
  mutate(drivmiddel =coalesce(drivmiddel, "Total")) %>% 
  fill(type) %>% 
  summarise(across(where(is.double), sum),
            .by = c("type","drivmiddel")) %>% 
  pivot_longer(cols = matches("\\d+"), names_to = "aar", values_to = "antal") %>% 
  mutate(antal = round(antal, 0))

KF_tal <- KF_bestand %>% 
  filter(type=="Varebiler", drivmiddel =="BEV") %>% 
  mutate(aar = parse_number(aar),
         x_axis = str_glue("1. januar {aar+1} forventet (KF24)"),
         oprindelse = "KF") %>% 
  filter(aar %in% c(as.numeric(nyeste_aar), as.numeric(nyeste_aar)+1)) %>% # TODO: Dette skal rettes når der kommer tal fra KF24
  select(INDHOLD=antal, x_axis, oprindelse)

```

```{r}

#Data figur 5. udvikling i bestanden
data_fig_4 <- data_bil_1 |> 
  mutate(DRIV_1 = ifelse(DRIV %in% c("Benzin", "Diesel"), "Fossil biler", DRIV) |> 
           factor(levels = c("El", "Plug-in-hybrid", "Fossil biler", "Drivmidler i alt")),
         AAR = year(DATE)) |> 
  summarise(INDHOLD = sum(INDHOLD),
            .by = c("DRIV_1", "AAR", "DATE") ) |> 
  mutate(UDV_ANTAL_BIL = INDHOLD-lag(INDHOLD, as.numeric(Nummer_sidste_md)),
         .by = c("DRIV_1")) %>% 
  filter(month(DATE)==Nummer_sidste_md, AAR>2019)


tal <- data_fig_4 |> 
  filter(!is.na(UDV_ANTAL_BIL))

tal_el_2019 <- tal |> filter(DRIV_1=="El", AAR=="2020") |> pull("UDV_ANTAL_BIL")
tal_el_2023 <- tal |> filter(DRIV_1=="El", AAR==nyeste_aar) |> pull("UDV_ANTAL_BIL")
tal_fos_2019 <- tal |> filter(DRIV_1=="Fossil biler", AAR=="2020") |> pull("UDV_ANTAL_BIL")
tal_fos_2023 <- tal |> filter(DRIV_1=="Fossil biler", AAR==nyeste_aar) |> pull("UDV_ANTAL_BIL")

#SKAL DETTE ÆNDRES TIL "VAREBILER"????


max_year_P_I_H<- data_fig_4 %>%
  filter(DRIV_1 == "Plug-in-hybrid") %>%
  slice(which.max(UDV_ANTAL_BIL)) %>%
  pull(AAR)


```